# Configuration for the Active Proxy service peer.
# The peerId is mandatory.
# The host and port are optional. If omitted, the client will perform a DHT lookup to resolve
# the peer’s network address. If provided, these values will be used directly as the peer’s address.
service:
  peerId: 7BcZ49fhqaxpNA9BwABy4gpZqWrfMX8Xytze426tvxrN
  host: 47.101.142.224
  port: 9090

# Client credentials.
# The user id and the device private key are required.
client:
  userId: ${YOUR_USER_ID}
  devicePrivateKey: ${YOUR_DEVICE_PRIVATE_KEY}

# Upstream server configuration.
# The host and port are mandatory, The scheme is optional, defaults to "tcp://".
upstream:
  host: 127.0.0.1
  port: 8888
  scheme: http://

# Enables name-based access to the proxied endpoint.
# This feature depends on the service peer’s capabilities and the client’s subscription level.
# Optional. Defaults to false.
nameAccess: false

# Controls whether the client should announce its proxied endpoint to the DHT network for peer discovery.
# Optional. Defaults to false.
announcePeer: false

logLevel: debug
logFile: default.log
logConsole: true
