# Configuration for the Active Proxy service peer.
# The peerId is mandatory.
# The host and port are optional. If omitted, the client will perform a DHT lookup to resolve
# the peer’s network address. If provided, these values will be used directly as the peer’s address.
service:
  peerId: 8okgUMSQHfnvTSEB9rjquvF6mMbhnPZD93Xir95BpD2b
  host: 66.42.74.13
  port: 9090

# Client credentials.
# The user id and the device private key are required.
client:
  # userPrivateKey: WD4dkEd3Jv9itgYj8hW7VvgBu4muGCTyuaQcCKQH4EZbW1rUyiEu3DaZ7td72er17kJkEUTsjUsgTSk8stpZE62
  userId: 3iighwS988Gp3axKuB2VbUU39DYym3WJcGyxX1MUHDQr
  devicePrivateKey: 25mK4Jzkk8CRnTuEQ77D7j2k87RTnXP8JLHAMvqpchNhB8eAk7VASG32uQoLd8FrtvwmP26R7RABi79HRaqCibbb

# Upstream server configuration.
# The host and port are mandatory, The scheme is optional, defaults to "tcp://".
upstream:
  host: 127.0.0.1
  port: 8888
  scheme: http://

# Enables name-based access to the proxied endpoint.
# This feature depends on the service peer’s capabilities and the client’s subscription level.
# Optional. Defaults to false.
nameAccess: false

# Controls whether the client should announce its proxied endpoint to the DHT network for peer discovery.
# Optional. Defaults to false.
announcePeer: false
